codecov:
  branch: master
  strict_yaml_branch: master
  require_ci_to_pass: yes
  bot: "codecov-io"
  max_report_age: 48
  disable_default_path_fixes: no

coverage:
  precision: 2
  round: down
  range: "60...90"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "docs"
  - "**/__init__.py"
  - "**/**/__init__.py"
  - "docs"
  - "tests"
  - "_version.py"
  - "__init__.py"
  - "**/__init__.py"
  - "due.py"
  - ".*rc"
  - "versioneer.py"
  - "setup.py"
  - "phys2denoise/tests"
  - "phys2denoise/_version.py"
  - "phys2denoise/__init__.py"
  - "phys2denoise/**/__init__.py"
  - "phys2denoise/due.py"
  - "phys2denoise/.*rc"
  - "phys2denoise/versioneer.py"
  - "phys2denoise/setup.py"


comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
